# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Sector')),
            ],
        ),
    ]
