# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20161001_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalformfield',
            name='value',
        ),
    ]
